import Image from "next/image";
import Link from "next/link";
import { HomeOrganizingPriceCalculator } from "@/src/components/HomeOrganizingPriceCalculator";
import { createPageMetadata } from "@/src/lib/metadata";

export const metadata=createPageMetadata({title:"정리수납 비용안내",description:"정리수납 평균 비용과 공간 면적, 정리 범위, 가족 수와 수납 컨설팅에 따른 비용 기준을 확인하세요.",path:"/prices-tidyup"});
const factors=[["정리 면적","공간이 넓을수록 증가","평수보다 실제 정리할 수납장의 수를 함께 확인합니다."],["대상 공간","부분 정리 또는 집 전체","옷방·주방·팬트리처럼 물품이 많은 공간은 시간이 늘어납니다."],["가족과 물품 수","사용자 수에 따라 증가","같은 평수라도 물품과 생활 동선이 많으면 인원이 달라집니다."],["서비스 범위","정리 또는 컨설팅","직접 정리와 유지 방법 설계를 구분해 선택합니다."]] as const;
const faq=[["수납용품을 미리 사야 하나요?","아닙니다. 기존 수납장과 물품을 먼저 확인한 뒤 필요한 규격과 수량만 안내합니다."],["집 전체가 아니라 한 공간만 가능한가요?","옷방, 주방, 팬트리, 베란다처럼 필요한 공간만 선택할 수 있습니다."],["정리 후 다시 어지러워지지 않을까요?","사용 빈도와 가족 동선을 기준으로 위치를 정하고 유지 규칙이 필요한 경우 컨설팅을 함께 선택할 수 있습니다."]] as const;
export default function TidyupPricePage(){return <main className="tidy-price-page"><section className="tidy-price-hero"><div className="container"><div className="tidy-price-hero__copy"><h1>예쁜 수납보다<br/>다시 찾기 쉬운<br/>자리를 만듭니다.</h1><p>정리수납 비용은 집 전체 평수보다 정리할 공간과 물품 수에서 달라집니다. 필요한 곳만 고르고 유지 방법까지 선택하세요.</p><div><Link className="button button--primary" href="/estimate?service=home-organizing">사진으로 무료견적</Link><a className="button button--secondary" href="#tidy-calculator">예상비용 계산</a></div></div><figure><div className="tidy-price-hero__scene"><Image alt="정리수납 전문가가 주방과 옷장의 물품을 사용 동선에 맞게 분류하고 배치하는 현장" fill priority sizes="(max-width:900px) 100vw,52vw" src="/generated/home-organizing-hero-v1.png"/></div><figcaption><span>꺼내기</span><span>분류</span><span>배치</span><span>유지</span></figcaption></figure><div className="tidy-price-hero__numbers"><div><strong>20만원</strong><span>최소</span></div><div><strong>48만원</strong><span>대표 평균</span></div><div><strong>300만원</strong><span>최대</span></div></div></div></section><section className="tidy-calculator-wrap" id="tidy-calculator"><div className="container"><HomeOrganizingPriceCalculator/></div></section><section className="tidy-price-factors"><div className="container"><div className="tidy-price-factors__heading"><h2>평수 하나로는<br/>견적이 정해지지 않습니다.</h2><p>카피 사이트에서 반복되는 비용 요인 네 가지만 추렸습니다.</p></div><div className="tidy-price-factors__list">{factors.map(([title,price,description])=><article key={title}><h3>{title}</h3><strong>{price}</strong><p>{description}</p></article>)}</div></div></section><section className="tidy-price-story"><div className="container"><figure><Image alt="수납장 규격을 재고 생활용품을 사용 빈도별로 나누는 정리수납 작업" fill sizes="(max-width:820px) 100vw,50vw" src="/generated/home-organizing-hero-v1.png"/></figure><div><h2>정리는 비우는 일이 아니라<br/>사용 순서를 정하는 일입니다.</h2><ol><li><b>전부 꺼내기</b><span>숨어 있던 물품까지 한 번에 확인합니다.</span></li><li><b>사용 기준 분류</b><span>빈도와 가족별 사용자를 기준으로 나눕니다.</span></li><li><b>동선에 맞춰 배치</b><span>자주 쓰는 물건을 가장 쉬운 위치에 둡니다.</span></li><li><b>유지 규칙 전달</b><span>다시 쌓이지 않도록 자리와 수량을 정합니다.</span></li></ol></div></div></section><section className="section section--subtle"><div className="container waste-price-faq"><div><h2>견적 전<br/>자주 묻는 질문</h2></div><div>{faq.map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</div></div></section><section className="waste-price-cta"><div className="container"><div><h2>정리가 필요한 수납장을 열어 보여주세요.</h2><p>방 전체보다 옷장·서랍·팬트리 내부 사진이 견적에 더 도움이 됩니다.</p></div><Link className="button button--light" href="/estimate?service=home-organizing">정리수납 사진견적</Link></div></section></main>}
