import Link from "next/link";
import { AdminDataRefresh } from "@/src/components/admin/AdminDataRefresh";
import { isDatabaseConfigured } from "@/db";
import { isAdminConfigured } from "@/src/server/admin-auth";
import { estimateStatusLabels,estimateStatuses,listAdminEstimates,type EstimateStatus } from "@/src/server/admin-estimates";
import { getAdminSession } from "@/src/server/admin-session";
import { services } from "@/src/domain/site";
import { loginAdmin,logoutAdmin } from "./actions";

type SearchParams=Promise<{status?:string;q?:string;error?:string;deleted?:string}>;
const serviceNames=new Map<string,string>(services.map((service)=>[service.slug,service.name]));
function dateTime(value:string){return new Intl.DateTimeFormat("ko-KR",{dateStyle:"medium",timeStyle:"short",timeZone:"Asia/Seoul"}).format(new Date(value));}

export default async function AdminPage({searchParams}:{searchParams:SearchParams}){
  const params=await searchParams;const session=await getAdminSession();
  if(!session)return <main className="admin-login"><section><div className="admin-brand"><i>S</i><span><strong>솔로몬종합청소</strong><small>ESTIMATE ADMIN</small></span></div><h1>견적 관리 로그인</h1><p>고객 연락처와 현장 사진이 포함된 내부 전용 화면입니다.</p>{!isAdminConfigured()?<div className="admin-alert">Vercel 환경변수에 ADMIN_EMAIL, ADMIN_PASSWORD, ADMIN_SESSION_SECRET을 설정해야 로그인할 수 있습니다.</div>:null}{params.error?<div className="admin-alert">이메일 또는 비밀번호를 확인해주세요.</div>:null}<form action={loginAdmin}><label>관리자 이메일<input autoComplete="username" defaultValue={process.env.ADMIN_EMAIL??""} name="email" required type="email"/></label><label>비밀번호<input autoComplete="current-password" name="password" required type="password"/></label><button disabled={!isAdminConfigured()} type="submit">로그인</button></form><Link href="/">사이트로 돌아가기</Link></section></main>;
  if(!isDatabaseConfigured())return <main className="admin-shell"><header className="admin-topbar"><div className="admin-brand"><i>S</i><span><strong>견적 관리</strong><small>{session.email}</small></span></div><form action={logoutAdmin}><button type="submit">로그아웃</button></form></header><section className="admin-setup"><div><h1>견적 저장소 연결이 필요합니다.</h1><p>관리자 로그인은 정상입니다. 현재 실행 환경에 <code>POSTGRES_URL</code>이 없어 견적 목록을 불러올 수 없습니다.</p><ol><li><div>Vercel 프로젝트의 Storage에서 Postgres 호환 데이터베이스를 연결합니다.</div></li><li><div>로컬에서는 Vercel 환경변수를 <code>.env.local</code>로 내려받습니다.</div></li><li><div><code>pnpm db:migrate</code>를 실행해 견적 테이블을 준비합니다.</div></li></ol></div></section></main>;
  const estimates=await listAdminEstimates(params.status,params.q);const counts=Object.fromEntries(estimateStatuses.map((status)=>[status,estimates.filter((item)=>item.status===status).length]));
  return <main className="admin-shell"><header className="admin-topbar"><div className="admin-brand"><i>S</i><span><strong>견적 관리</strong><small>{session.email}</small></span></div><form action={logoutAdmin}><button type="submit">로그아웃</button></form></header><div className="admin-workspace"><aside><strong>운영 메뉴</strong><nav><Link className="is-active" href="/admin">견적 문의 <span>{estimates.length}</span></Link></nav><p>접수된 고객 문의와 처리 상태를 관리합니다.</p></aside><section className="admin-content"><header><div><h1>견적 문의</h1><p>최근 접수순 최대 200건을 표시합니다.</p></div><AdminDataRefresh/></header>{params.deleted?<div className="admin-saved">견적 문의와 첨부 사진을 삭제했습니다.</div>:null}<div className="admin-stats"><article><span>신규</span><strong>{counts.received}</strong></article><article><span>상담·견적</span><strong>{counts.contacted+counts.quoted}</strong></article><article><span>예약</span><strong>{counts.scheduled}</strong></article><article><span>완료</span><strong>{counts.completed}</strong></article></div><form className="admin-filters"><input defaultValue={params.q} name="q" placeholder="접수번호, 이름, 연락처, 지역 검색"/><select defaultValue={params.status??""} name="status"><option value="">전체 상태</option>{estimateStatuses.map((status)=><option key={status} value={status}>{estimateStatusLabels[status]}</option>)}</select><button type="submit">검색</button></form><div className="admin-table-wrap"><table><thead><tr><th>접수</th><th>고객</th><th>서비스·지역</th><th>상태</th><th>접수 일시</th><th><span className="sr-only">상세</span></th></tr></thead><tbody>{estimates.map((estimate)=><tr key={estimate.id}><td><strong>{estimate.reference}</strong></td><td>{estimate.customer_name}<small>{estimate.phone}</small></td><td>{serviceNames.get(estimate.service)??estimate.service}<small>{estimate.area}</small></td><td><span className={`admin-status admin-status--${estimate.status}`}>{estimateStatusLabels[estimate.status as EstimateStatus]}</span></td><td>{dateTime(estimate.created_at)}</td><td><Link href={`/admin/estimates/${estimate.id}`}>상세 보기</Link></td></tr>)}</tbody></table>{!estimates.length?<div className="admin-empty">조건에 맞는 견적 문의가 없습니다.</div>:null}</div></section></div></main>;
}
