"use server";
import { del } from "@vercel/blob";
import { redirect } from "next/navigation";
import { getDatabaseClient } from "@/db";
import { getAdminSession } from "@/src/server/admin-session";
import { getAdminWorkCase } from "@/src/server/work-cases";
function value(formData: FormData, key: string, max: number) { return String(formData.get(key) ?? "").trim().slice(0, max); }
function validImageUrl(url: string) { return /^\/blog-images\/[\w.-]+$/.test(url) || /^work-cases\/[0-9a-f-]{36}\/(before|after)-[0-9a-f-]{36}\.webp$/i.test(url); }
async function removeBlob(url: string, replacement?: string) { if (url !== replacement && url.startsWith("work-cases/")) await del(url).catch(() => undefined); }
export async function saveWorkCase(formData: FormData) { if (!await getAdminSession()) redirect("/admin?error=session"); const id = value(formData, "id", 36) || crypto.randomUUID(); const title = value(formData, "title", 100); const category = value(formData, "category", 50); const description = value(formData, "description", 300); const beforeImageUrl = value(formData, "beforeImageUrl", 1000); const afterImageUrl = value(formData, "afterImageUrl", 1000); const displayOrder = Math.max(0, Math.min(999, Number.parseInt(value(formData, "displayOrder", 3), 10) || 0)); const published = formData.get("published") === "on"; if (!title || !category || !validImageUrl(beforeImageUrl) || !validImageUrl(afterImageUrl)) redirect(`/admin/cases/${id}?error=invalid`); const previous = await getAdminWorkCase(id); await getDatabaseClient().unsafe(`INSERT INTO work_cases (id,title,category,description,before_image_url,after_image_url,published,display_order,created_at,updated_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,NOW(),NOW()) ON CONFLICT (id) DO UPDATE SET title=$2,category=$3,description=$4,before_image_url=$5,after_image_url=$6,published=$7,display_order=$8,updated_at=NOW()`, [id,title,category,description,beforeImageUrl,afterImageUrl,published,displayOrder]); if (previous) await Promise.all([removeBlob(previous.before_image_url,beforeImageUrl),removeBlob(previous.after_image_url,afterImageUrl)]); redirect(`/admin/cases/${id}?saved=1`); }
export async function deleteWorkCase(formData: FormData) { if (!await getAdminSession()) redirect("/admin?error=session"); const id = value(formData,"id",36); const previous = await getAdminWorkCase(id); if (previous) { await getDatabaseClient().unsafe("DELETE FROM work_cases WHERE id = $1",[id]); await Promise.all([removeBlob(previous.before_image_url),removeBlob(previous.after_image_url)]); } redirect("/admin/cases?deleted=1"); }
