"use client";
import { upload } from "@vercel/blob/client";
import { useState } from "react";
import { deleteWorkCase,saveWorkCase } from "@/app/admin/cases/actions";
import { getWorkCaseImageSrc } from "@/src/components/WorkCaseGrid";
import { optimizeEstimatePhoto } from "@/src/domain/photo-optimization";
import type { WorkCase } from "@/src/server/work-cases";
type Side="before"|"after";
export function WorkCaseEditor({item,draftId}:{item?:WorkCase;draftId?:string}){const[id]=useState(item?.id??draftId??"");const[images,setImages]=useState({before:item?.before_image_url??"",after:item?.after_image_url??""});const[uploading,setUploading]=useState<Side|null>(null);const[message,setMessage]=useState("");async function choose(side:Side,file?:File){if(!file)return;setUploading(side);setMessage("");try{const optimized=await optimizeEstimatePhoto(file);const blob=await upload(`work-cases/${id}/${side}-${crypto.randomUUID()}.webp`,optimized,{access:"private",handleUploadUrl:"/api/admin/work-cases/upload",contentType:"image/webp"});setImages((current)=>({...current,[side]:blob.pathname}));}catch(error){setMessage(error instanceof Error?error.message:"사진을 업로드하지 못했습니다.");}finally{setUploading(null);}}return <form action={saveWorkCase} className="admin-case-editor"><input name="id" type="hidden" value={id}/><input name="beforeImageUrl" type="hidden" value={images.before}/><input name="afterImageUrl" type="hidden" value={images.after}/><section className="admin-case-images">{(["before","after"] as Side[]).map((side)=><label key={side}><span><b>{side==="before"?"작업 전":"작업 후"}</b><small>{uploading===side?"자동 축소 후 업로드 중…":"사진 선택"}</small></span><input accept="image/*,.heic,.heif" disabled={Boolean(uploading)} onChange={(event)=>void choose(side,event.target.files?.[0])} type="file"/>{images[side]?<img alt={side==="before"?"작업 전 미리보기":"작업 후 미리보기"} src={getWorkCaseImageSrc(images[side])}/>:<i>사진을 선택해주세요</i>}</label>)}</section>{message?<p className="admin-form-error" role="alert">{message}</p>:null}<section className="admin-case-fields"><label>사례 제목<input defaultValue={item?.title} maxLength={100} name="title" placeholder="예: 원룸 쓰레기집 청소" required/></label><label>카테고리<input defaultValue={item?.category} maxLength={50} name="category" placeholder="예: 특수청소" required/></label><label className="admin-case-fields__wide">짧은 설명<textarea defaultValue={item?.description} maxLength={300} name="description" placeholder="작업 범위와 변화가 드러나는 한두 문장" rows={4}/></label><label>노출 순서<input defaultValue={item?.display_order??0} max={999} min={0} name="displayOrder" type="number"/></label><label className="admin-case-publish"><input defaultChecked={item?.published??false} name="published" type="checkbox"/><span><b>사이트에 공개</b><small>끄면 관리자에서만 보입니다.</small></span></label></section><div className="admin-case-actions"><button disabled={Boolean(uploading)||!images.before||!images.after} type="submit">{item?"변경사항 저장":"작업사례 등록"}</button>{item?<button className="admin-case-delete" formAction={deleteWorkCase} formNoValidate name="id" onClick={(event)=>{if(!window.confirm("이 작업사례와 업로드한 사진을 삭제할까요?"))event.preventDefault();}} type="submit" value={id}>삭제</button>:null}</div></form>}
