import type { CustomerReview } from "../domain/customer-review.ts";

/** Layout-only sample content. Replace through the review server boundary before publishing real claims. */
export const customerReviewFallback: readonly CustomerReview[] = [
  { id: "sample-001", serviceSlug: "move-in-cleaning", serviceLabel: "입주·이사·준공청소", title: "새집에 들어가는 기분이 제대로 났어요.", body: "창틀 먼지와 주방 안쪽까지 꼼꼼하게 봐주셨고, 마무리할 때 함께 확인해주셔서 안심됐어요. 이사 전날이라 걱정했는데 일정도 잘 맞춰주셨습니다.", rating: 5, region: "서울", displayName: "김○○", publishedAt: "2026-07-28", source: "placeholder" },
  { id: "sample-002", serviceSlug: "waste-disposal", serviceLabel: "폐기물처리", title: "사진으로 먼저 견적을 받아 편했어요.", body: "버릴 가구와 짐이 많았는데 사진을 보고 필요한 차량과 인원을 미리 알려주셨어요. 현장에서도 설명한 범위대로 빠르게 정리해주셨습니다.", rating: 5, region: "경기", displayName: "박○○", publishedAt: "2026-07-23", source: "placeholder" },
  { id: "sample-003", serviceSlug: "hoarding-cleanup", serviceLabel: "쓰레기집청소", title: "민망한 마음 없이 상담할 수 있었어요.", body: "상황을 조용히 들어주시고 남겨야 할 물건부터 하나씩 확인해주셨어요. 폐기물 수거와 청소를 같이 진행해 생각보다 빠르게 일상을 되찾았습니다.", rating: 5, region: "인천", displayName: "이○○", publishedAt: "2026-07-18", source: "placeholder" },
  { id: "sample-004", serviceSlug: "deep-cleaning", serviceLabel: "특수청소", title: "냄새 때문에 고민했는데 한결 편해졌어요.", body: "오염된 부분과 소독이 필요한 구역을 먼저 설명해주셔서 믿음이 갔어요. 작업 후 확인 방법과 환기 안내까지 세심하게 챙겨주셨습니다.", rating: 5, region: "대전", displayName: "최○○", publishedAt: "2026-07-11", source: "placeholder" },
  { id: "sample-005", serviceSlug: "estate-clearing", serviceLabel: "유품정리", title: "남겨둘 물건을 먼저 확인해주셨어요.", body: "급하게 버리지 않고 사진과 서류를 따로 모아주셔서 감사했습니다. 가족이 확인할 시간을 주면서 정리와 청소를 차분하게 진행해주셨어요.", rating: 5, region: "충남", displayName: "정○○", publishedAt: "2026-07-03", source: "placeholder" },
  { id: "sample-006", serviceSlug: "home-organizing", serviceLabel: "정리수납", title: "정리한 뒤에도 유지하기 쉬워졌어요.", body: "자주 쓰는 물건과 계절용품을 나눠 배치해주셨어요. 가족 동선에 맞춰 정리해주니 어디에 무엇이 있는지 바로 알 수 있어 편합니다.", rating: 5, region: "서울", displayName: "윤○○", publishedAt: "2026-06-26", source: "placeholder" },
  { id: "sample-007", serviceSlug: "waste-disposal", serviceLabel: "폐기물처리", title: "큰 가구까지 한 번에 정리했어요.", body: "엘리베이터가 없는 곳이라 걱정했는데 반출 조건을 미리 확인해주셨어요. 수거가 끝난 뒤 주변까지 정돈해주셔서 깔끔했습니다.", rating: 5, region: "부산", displayName: "한○○", publishedAt: "2026-06-18", source: "placeholder" },
  { id: "sample-008", serviceSlug: "move-in-cleaning", serviceLabel: "입주·이사·준공청소", title: "주방과 욕실이 특히 만족스러웠어요.", body: "신경 쓰이던 수전 물때와 주방 기름 자국을 집중적으로 봐달라고 말씀드렸는데 요청한 부분을 꼼꼼히 확인해주셨습니다.", rating: 5, region: "경기", displayName: "오○○", publishedAt: "2026-06-09", source: "placeholder" },
  { id: "sample-009", serviceSlug: "hoarding-cleanup", serviceLabel: "쓰레기집청소", title: "여러 업체에 설명하지 않아도 돼서 좋았어요.", body: "폐기물 수거부터 오염 청소까지 한곳에서 상담하니 마음이 놓였어요. 작업 순서와 소요 시간을 미리 알려주셔서 준비하기도 수월했습니다.", rating: 5, region: "광주", displayName: "서○○", publishedAt: "2026-05-30", source: "placeholder" },
] as const;
